---
version: 1
aliases:
  - path: /api/discovery/namespaces/{namespace}/suggest-values
    method: post
    canonical_operation_id: ves.io.schema.discovery_cloud.CustomAPI.SuggestValues
    alternate_operation_id: ves.io.schema.discovered_service.CustomAPI.SuggestValues
    canonical_service_identity: discovery_cloud
    alternate_service_identity: discovered_service
